#include "src/gfx_mk.c"
//#include "src/gdisp/gdisp.mk.c"

//#include "src/gdisp/mcufont/mf_font.c"
//#include "src/gdisp/mcufont/mf_rlefont.c"
//#include "src/gdisp/mcufont/mf_bwfont.c"
//#include "src/gdisp/mcufont/mf_scaledfont.c"
//#include "src/gdisp/mcufont/mf_encoding.c"
//#include "src/gdisp/mcufont/mf_justify.c"
//#include "src/gdisp/mcufont/mf_kerning.c"
//#include "src/gdisp/mcufont/mf_wordwrap.c"
//
//#include "src/gdisp/gdisp.c"
//#include "src/gdisp/gdisp_fonts.c"
//#include "src/gdisp/gdisp_pixmap.c"
//#include "src/gdisp/gdisp_image.c"
//#include "src/gdisp/gdisp_image_native.c"
//#include "src/gdisp/gdisp_image_gif.c"
//#include "src/gdisp/gdisp_image_bmp.c"
//#include "src/gdisp/gdisp_image_jpg.c"
//#include "src/gdisp/gdisp_image_png.c"
//